### ISSUE TITLE
Optimal chunk size for parsing performance.

### ISSUE THREAD

**Issue by Falven** [nodejs/llhttp#112]
Has there been any research/observations on the optimal buffer/chunk sizes for parsing performance?
Is it faster to parse every character as it arrives or faster to store them in a buffer of size N characters and then parse the buffer?
Maybe it's faster to parse requests line-by-line?

**Comment by indutny** [comment]
Hello!

I'd say the more you give to the parser the better it runs as it can run some vectorized CPU instructions when there's a lot of data. That being said, the best idea might be to just give it data as soon as you receive it without doing any buffering. The fact that the parser doesn't copy any memory means that the app can give llhttp the networking buffer straight after receiving the bytes.

Let me know if I can answer any other questions!

**Comment by Falven** [comment]
> Hello!
> 
> I'd say the more you give to the parser the better it runs as it can run some vectorized CPU instructions when there's a lot of data. That being said, the best idea might be to just give it data as soon as you receive it without doing any buffering. The fact that the parser doesn't copy any memory means that the app can give llhttp the networking buffer straight after receiving the bytes.
> 
> Let me know if I can answer any other questions!

Well, in my case what I'm doing is buffering the whole request, since you need the whole request for most standard usage cases, but as I'm buffering I'm calling the parser to identify the different parts of the buffer as the different HttpRequest/Response elements (not allocating any additional memory.) And I'm parsing the request line-by-line. Once the buffer reads a line, I parse it. But it could be faster to parse character by character instead, idk. I will do some research.

**Comment by pallas** [comment]
In most cases, I'd assume the network I/O or the business logic are the biggest overhead, not the HTTP parsing. You really don't need to parse \r\n by \r\n, llhttp will do that for you. I certainly would not call parse character by character, since you'll make a function call and jump into the state machine every single time, and callbacks you'd get in a bigger buffer will happen byte-by-byte instead of in chunks as with a larger buffer.

Definitely note that no matter how big your buffer is, you might get multiple of the same callback if some important part of the stream is split across buffers, e.g. for a field named "ABCDEFG", you might get an `on_header_field("A")` followed by an `on_header_field("BCDE")` followed by an `on_header_field("FG")` followed by an `on_header_field_complete()` if your buffer is four bytes. I don't know your particular application but `PIPE_BUF` is typically a good generic size for reads; YMMV.

In the multiple-request case, I'm not sure how you know that a whole request has even been made without doing something similar to what llhttp parser is already doing and my suggestion would be to let llhttp do it. That is: create a fixed sized buffer of a reasonable size, read into it with a reasonable timeout, let llhttp parse whatever is in the buffer, save anything you need later via callbacks, and then wipe out and reuse the existing buffer. Anything else is either very subtle & complex, or just reinventing the wheel.

**Comment by Falven** [comment]
Thank you pallas.
I agree; this is probably the optimal case for my situation. My situation being a single threaded webserver that can only handle one request at a time. But I would assume that on a webserver with a threadpool handling multiple concurrent requests it may be better to parse as data comes in since the networking is going to be much slower than the parsing...
