### ISSUE TITLE
Build without requiring typescript

### ISSUE THREAD

**Issue by jellelicht** [nodejs/llhttp#14]
As a packager, it would be nice to be able to remove typescript as a build-time dependency of this package, considering that one might want to bootstrap node from source without requiring an existing node environment. 

Are there any plans to remove the ad hoc code generation parts using TypeScript?

**Comment by indutny** [comment]
It would really hard to remove TypeScript from llhttp and [llparse][llparse]. I don't see any problem bootstrapping Node, though. The releases don't have any JavaScript or TypeScript files at all: https://github.com/nodejs/llhttp/releases

What do you mean by `ad hoc code generation`?

[llparse]: https://github.com/nodejs/llparse

**Comment by jellelicht** [comment]
I mean bootstrapping from actual source, in the sense as promoted by https://reproducible-builds.org/. This boils down to not wanting to build from pre-generated files such as what you are offering in the releases.

Also regarding the ad hoc code generation, which I did not mean to sound harsh, is referring to the string manipulation as in `c-headers.ts`.

Thanks for the consideration and the fast response.

**Comment by jellelicht** [comment]
Alternatively, would it be possible to build node without depending on llhttp at all?

**Comment by indutny** [comment]
I was thinking about your request a bit more since last reply. Removing TypeScript won't make bootstrapping possible. This project is still a collection of tens of files distributing over several repositories. Even if it wouldn't be in TypeScript, node has to be able to run them and resolve dependencies.

The build is, however, 100% reproducible. The generated code doesn't depend on either TypeScript version or environment. It is exactly the same given particular parser description that llhttp has.
