### ISSUE TITLE
HPE_INVALID_METHOD possible causing reason?

### ISSUE THREAD

**Issue by JackLiar** [nodejs/llhttp#27]
I encountered some HPE_INVALID_METHOD errors while parsing http protocol(llhttp release branch c api). However, the methods are just normal "GET" "POST". **There are spaces(\x20) between http methods and urls.**

I tried and got the err positions, but they all seems far away from the request method. Some are in the user-agent, some are in the host

I know nothing about TypeScript, I just searched for "INVALID_METHOD" and found the only possible reason would be no space before url. But in the c code(llhttp.c), there're lots of goto pointing to the "Invalid method" piece of code.

Could u guys help figuring it out?

**Comment by indutny** [comment]
Hello @JackLiar !

Thank you for submitting this.

The spaces between methods and urls are indeed required. However it seems that it is impossible to make much progress without having a test case. Do you have a `.js` file that reproduces your problem, or perhaps just the HTTP request itself?

I'd be happy to look into it when more details will be available.

Thank you,
Fedor.

**Comment by JackLiar** [comment]
@indutny It seems like I didn't use the c api in the right way.

Is it necessary to run llhttp_init(parser, type, settings) before each llhttp_execute?

Cause I dig it into the generated c code, and find the content length of parser is not zero when I tries to parse another http payload. And it causes the pointer pointing to a wrong location inside the http payload not the beginning of the payload.

```C
case s_n_llhttp__internal__n_consume_content_length:
    s_n_llhttp__internal__n_consume_content_length: {
      size_t avail;
      size_t need;
      
      avail = endp - p;
      need = state->content_length;  // For example content_length is 127
      if (avail >= need) {
        p += need;                                 // After this, p is not pointing to the right position
        state->content_length = 0;
        goto s_n_llhttp__internal__n_span_end_llhttp__on_body;
      }
```

The code and example payload is inside a private network, and I failed to reproduce this on my computer now, so this is probably all the information I could provide now :(

**Comment by indutny** [comment]
It is not necessary to call `llhttp_init()` before each request.

As in the code sample that you quoted, the `content_length` is set once the `Content-Length` header was parsed (or one a header of a `Chunked-Encoding` chunk was parsed) and is decremented gradually until the body is parsed. If it is non-zero at the start of the next request - this should normally mean that the previous request has ended prematurely without sending full body to your server.

---

User, however, is expected to call `llhttp_init()` if the connection was closed and the same parser instance is to be used for other connection. The initialization is valid only for a single connection since premature close of the socket might leave the parser in an incomplete state.

**Comment by JackLiar** [comment]
I see. Thx for ur help :)
