### ISSUE TITLE
Misleading 'Parse Error: Expected HTTP/' when `Content-Length` mismatch

### ISSUE THREAD

**Issue by yshing** [nodejs/llhttp#445]
When handling malformed http response that contains a body but having `content-length` set to 0, the error should say it expecting EOF, but it says `Expected HTTP/` instead.
```js
// Sample string from node.js clientError: err.rawPacket.toString()
'HTTP/1.1 400 Bad Request\r\n' +
  'Date: Thu, 25 Jul 2024 08:28:42 GMT\r\n' +
  'Content-Type: application/json\r\n' +
  'Content-Length: 0\r\n' +
  'Connection: close\r\n' +
  '\r\n' +
  'Not allowed'
// ^-- Here it throws the error `HPE_INVALID_CONSTANT`
// err.code: `HPE_INVALID_CONSTANT`
// err.reason: 'Expected HTTP/'
// err.bytesParsed: 135
// err.rawPacket[err.bytesParsed]: 'N'
```

**Comment by ShogunPanda** [comment]
Since the `Content-Length` is `0`, the first message ends after the second `\r\n`.
The `Expected HTTP/` comes as llhttp see `Not allowed` as part of a new response (which should start with `HTTP/1.1`.
You can notice this by looking at `err.bytesParsed: 135` and `err.rawPacket[err.bytesParsed]: 'N'` (and there is n other "N" in the response stream."
