### ISSUE TITLE
How do I get the parsed length in on_message_complete callback?

### ISSUE THREAD

**Issue by xcyl** [nodejs/llhttp#60]
How do I get the parsed length in on_message_complete callback?

**Comment by xcyl** [comment]
If I change the callback(on_message_complete(llhttp_t* parser)) to this(on_message_complete(llhttp_t* parser, const char* at, std::size_t length)), I can get the length (at - begin). But that's not necessary.

**Comment by davidhcefx** [comment]
Is it possible to retrieve the end-of-message index by accessing `parser->_index`, `parser->_current` or something else?
Because sometimes what we need is the span of a HTTP request message, where the current solution is to keep track of each `on_header_value`.

```c
// llhttp.h
typedef struct llhttp__internal_s llhttp__internal_t;
struct llhttp__internal_s {
  int32_t _index;
  void* _span_pos0;
  void* _span_cb0;
  int32_t error;
  const char* reason;
  const char* error_pos;
  void* data;
  void* _current;
  uint64_t content_length;
  uint8_t type;
  uint8_t method;
  uint8_t http_major;
  uint8_t http_minor;
  uint8_t header_state;
  uint8_t lenient_flags;
  uint8_t upgrade;
  uint8_t finish;
  uint16_t flags;
  uint16_t status_code;
  void* settings;
};
```

**Comment by davidhcefx** [comment]
My input is a stream of bytes, and I want to know the span of the whole request when it invoked `on_message_complete` callback. I wonder if there is a way to achieve this without modifying the `llhttp` code?

My first thought was to hook `on_header_value` and `on_body` to update a pointer always pointing to the last byte. However, this would not cover the case when there is only a single REQUEST_LINE and no headers at all, because there is no callback for that. Another approach would be scanning and partitioning the input by `CRLF`, and feed each segments separately to the parser, but this doesn't seems to be an elegant way. Do you have any thoughts on this?

**Comment by indutny** [comment]
Here's an idea. You can store a pointer to your structure in the `->data` field of the parser, and among other things store the number of bytes parsed since the `on_message_begin` called. Since the data in callbacks is always relative to the input pointer that was given to the `llhttp_execute()` - it is always possible to compute at what input position each callback was invoked. You could use `error_pos` or just input size (depending on `llhttp_execute()` return value) to move by whole chunks forward.

I'm not entirely against adding a field like that to the parser, but each such addition will slow it down for users that don't need this feature and implementing this feature seems generally not to complicated.

**Comment by davidhcefx** [comment]
Thanks for your instant feedback!
I have tried `llhttp_get_error_pos()`, but it seems to only return a non-null value when an error occurred. After hacking around, I found modifying the code the easiest way of solving this problem. So in case someone is interested, here is what I modified:

```diff
diff --git a/src/native/api.c b/src/native/api.c
index 8a4bdd2..b898d0c 100644
--- a/src/native/api.c
+++ b/src/native/api.c
@@ -113,7 +113,7 @@ void llhttp_settings_init(llhttp_settings_t* settings) {
 }
 
 
-llhttp_errno_t llhttp_finish(llhttp_t* parser) {
+llhttp_errno_t llhttp_finish(llhttp_t* parser, const char* data, size_t len) {
   int err;
 
   /* We're in an error state. Don't bother doing anything. */
@@ -123,7 +123,7 @@ llhttp_errno_t llhttp_finish(llhttp_t* parser) {
 
   switch (parser->finish) {
     case HTTP_FINISH_SAFE_WITH_CB:
-      CALLBACK_MAYBE(parser, on_message_complete, parser);
+      CALLBACK_MAYBE(parser, on_message_complete, parser, data, len);
       if (err != HPE_OK) return err;
 
     /* FALLTHROUGH */
@@ -307,7 +307,7 @@ int llhttp__on_headers_complete(llhttp_t* s, const char* p, const char* endp) {
 
 int llhttp__on_message_complete(llhttp_t* s, const char* p, const char* endp) {
   int err;
-  CALLBACK_MAYBE(s, on_message_complete, s);
+  CALLBACK_MAYBE(s, on_message_complete, s, p, endp - p);
   return err;
 }
 
diff --git a/src/native/api.h b/src/native/api.h
index 7fdbfc1..bd5b9eb 100644
--- a/src/native/api.h
+++ b/src/native/api.h
@@ -40,7 +40,7 @@ struct llhttp_settings_s {
   llhttp_data_cb on_body;
 
   /* Possible return values 0, -1, `HPE_PAUSED` */
-  llhttp_cb      on_message_complete;
+  llhttp_data_cb on_message_complete;
 
   /* When on_chunk_header is called, the current chunk length is stored
    * in parser->content_length.
@@ -131,7 +131,7 @@ llhttp_errno_t llhttp_execute(llhttp_t* parser, const char* data, size_t len);
  * request was terminated safely. Otherwise a error code would be returned.
  */
 LLHTTP_EXPORT
-llhttp_errno_t llhttp_finish(llhttp_t* parser);
+llhttp_errno_t llhttp_finish(llhttp_t* parser, const char* data, size_t len);
 
 /* Returns `1` if the incoming message is parsed until the last byte, and has
  * to be completed by calling `llhttp_finish()` on EOF
```

After that, the `at` parameter in the new `on_message_complete` callback would point next to the last byte of the previous request. Example:

```http
HEAD / HTTP/1.1\r\n\r\nGET / HTTP/1.1\r\nHost: www.google.com\r\nAccept: */*\r\n\r\nPUT / HTTP/1.1\r\nContent-Length: 10\r\n\r\nhelloworldPOST / HTTP/1.0
const char* at = "GET / HTTP/1.1..."
const char* at = "PUT / HTTP/1.1..."
const char* at = "POST / HTTP/1.0"
```
