### ISSUE TITLE
Unexpected UNEXPECTED_CONTENT_LENGTH error with lenient parsing

### ISSUE THREAD

**Issue by flotwig** [nodejs/llhttp#69]
Current behavior: If both Content-Length and Transfer-Encoding: chunked are set on a response, an UNEXPECTED_CONTENT_LENGTH error is thrown, regardless of if llhttp is operating in lenient mode or not.

Expected behavior: If both Content-Length and Transfer-Encoding: chunked are set on a response, an UNEXPECTED_CONTENT_LENGTH error is thrown, but only if llhttp is NOT operating in lenient mode.

Relevant comment: https://github.com/nodejs/llhttp/blob/e5c3017cca47736fea5747cfa59f9e2a7dfec866/src/llhttp/http.ts#L576-L590

Based on this comment, the purpose of this error seems to be for security - to prevent request smuggling/response splitting. Node.js's name for the lenient flag is `insecureHTTPParser`, and to my mind, that means that the lenient flag should (insecurely) disable the `UNEXPECTED_CONTENT_LENGTH` error entirely. However, it does not seem to.

Test code (Node 12.15.0):

```js
http.createServer((req, res) => {
	res.setHeader('content-length', '0')
	res.setHeader('transfer-encoding', 'chunked')
	res.end()
}).listen(12345, () => {
	// expected: request succeeded
	// actual: Parse Error: Content-Length can't be present with chunked encoding
	http.request('http://localhost:12345', { insecureHTTPParser: true })
	.on('error', (err) => console.error(err.message))
	.on('response', () => console.log('request succeeded'))
	.end()
})
```

I'm proposing that, when in lenient mode, `Transfer-Encoding: chunked` should be allowed to co-exist with `Content-Length`, with `Content-Length` getting ignored. Does that make sense to the project maintainers? If so, I'll open up a PR.

**Comment by pallas** [comment]
@flotwig if you have  PR, I'd love to take a look

**Comment by derekargueta** [comment]
+1, this would nicely accompany [this PR](https://github.com/nodejs/http-parser/pull/518) to the the http-parser project for folks moving from http-parser to llhttp but rely on this functionality (such as myself currently 😄)

**Comment by derekargueta** [comment]
Reading the code a bit, it seems that the code in `llhttp__after_headers_complete` appropriately handles this:
https://github.com/nodejs/llhttp/blob/e5c3017cca47736fea5747cfa59f9e2a7dfec866/src/native/http.c#L50-L72

returning either 2 (`chunk_size_start`) or 4 (`body_identity_eof`), however the code in `buildHeaderValue` throws an error with `'Content-Length can\'t be present with chunked encoding'` in the `on_header_value` phase _before_ the `on_headers_complete` phase begins.

Relevant typescript snippet:
https://github.com/nodejs/llhttp/blob/e5c3017cca47736fea5747cfa59f9e2a7dfec866/src/llhttp/http.ts#L576-L614

A straightforward fix would be to remove the error case that is triggered if `FLAGS.CHUNKED | FLAGS.CONTENT_LENGTH` is set so that we make it to the `on_headers_complete` phase (and this callback is already protected by lenient mode) but since it changes behavior without a user opt-in, maybe we want to add an additional gating parameter for it like `allow_chunked_length` was added to http-parser?

**Comment by derekargueta** [comment]
@indutny does the above analysis make sense?

also to anyone else, I'm unable to run `npm run test` and have uploaded my compilation errors to [a Github gist](https://gist.github.com/derekargueta/b86c6006d978a5170efe2fb764593659). Would appreciate any help.
```
$ clang --version
clang version 11.0.0
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
$ npm --version
6.14.5
$ node --version
v14.4.0
```

**Comment by indutny** [comment]
Here's the fix for this issue: https://github.com/nodejs/llhttp/pull/77

---

@derekargueta I'm about to push the (possible) fix for `npm run test`. Stay tuned!

**Comment by indutny** [comment]
@derekargueta and it is live. `npm update` in `llhttp` folder should fix it. (`llparse-test-fixture@5.0.2` has the fix)
