### ISSUE TITLE
add parser->nread support

### ISSUE THREAD

**Issue by boostiewj** [nodejs/llhttp#75]
I want to get the bytes of http head  or  dump raw http head

**Comment by pallas** [comment]
I don't understand the ask here.

**Comment by boostiewj** [comment]
> I don't understand the ask here.
llhttp needs to support how many bytes are currently parsed.Because I want to get the total number of bytes in the HTTP header and  the total number of body,especially HTTP transmission in chunked format.

**Comment by pallas** [comment]
When execute completes without error, all of the bytes passed to it have been consumed. If you keep track of that, then inside a callback you should be able to use the `buffer` passed in to `llhttp_execute` and the pointer/length passed to the callback in order to find the additional offsets. I haven't tried this, so YMMV. If execute completes with error, then `error_pos - buffer` indicates how many bytes were actually processed prior to the error.

**Comment by indutny** [comment]
@pallas is right. The pointers that you get in the llhttp's callbacks are inside the data feed into `llhttp_execute`. You can use them to figure out the offsets and sizes.
